FROM node:20-alpine

WORKDIR /app

# pnpmをインストール
RUN corepack enable && corepack prepare pnpm@latest --activate

# 依存関係のインストール
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install

# アプリケーションのソースコードをコピー
COPY . .

EXPOSE 3000

# 開発サーバーを起動
CMD ["pnpm", "dev"] 