version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
    restart: always

  # 開発モード用の設定
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3006:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: pnpm dev 